---
title: "UN Regions"
author: "Evangeline Reynolds"
date: "12/30/2017"
output: pdf_document
---

```{r}
if (!dir.exists("../raw_data")) {
  dir.create("../raw_data")
}

if (!file.exists("../raw_data/un_region_members_2017-12-30.html"))  {
  download.file("https://www.un.org/depts/DGACM/RegionalGroups.shtml",
                destfile=paste0("../raw_data/un_region_members_", 
                                Sys.Date(), ".html"))
}

```

```{r}
library(dplyr)
library(stringr)
library(tidyr)
library(countrycode)
library(readr)
library(readtext)
country <- readLines("../raw_data/un_region_members_2017-12-30.html", 
                   encoding="UTF-8")

df = data_frame(country) %>% 
  filter(str_detect(country, "<li>|strong")) %>% 
  filter(!str_detect(country, "a href")) %>% 
  mutate(un_regional_group = ifelse(str_detect(country,"strong"), country, NA)) %>% 
  fill(un_regional_group) %>% 
  filter(un_regional_group != country) %>% 
  mutate(country = str_replace_all(country, "\\<.+?\\>", "")) %>% 
  mutate(country = str_replace_all(country, "&nbsp;", "")) %>% 
  mutate(un_regional_group = 
           str_replace_all(un_regional_group, "\\<.+?\\>", "")) %>% 
  mutate(un_regional_group = str_trim(un_regional_group))%>% 
  mutate(country = str_trim(country)) %>% 
  mutate(country_name = countrycode(country, "country.name", "country.name"))

df_fixes = df %>% filter(is.na(country_name))
df_fixes
  df_fixes = df_fixes %>% mutate(country = c("Central African Republic", "Democratic Republic of the Congo", 
"United Republic of Tanzania", 
"Democratic People's Republic of Korea", 
"The former Yugoslav 
 Republic of Macedonia")) %>% mutate(country_name = countrycode(country, "country.name", "country.name"))
  df_fixes
  
df <- bind_rows(df %>% filter(!is.na(country_name)), 
                df_fixes)
  
```



```{r}

df %>% filter(str_detect(country, "\\*"))

notes = data_frame(
  country = c("Kiribati", "Israel","Turkey", "United States of America"),
  un_region_notes = c(
"As of 2010, Kiribati (geographically in Oceania) is not a member of any regional group, despite other Oceania nations belonging to the Asian group. Despite its membership in the United Nations, Kiribati has never delegated a permanent representative to the UN.",
"In May 2000 Israel became a WEOG full member, on a temporary basis (subject to renewal), in WEOG's headquarters in the US, thereby enabling it to put forward candidates for election to various UN General Assembly bodies. In 2004 Israel obtained a permanent renewal to its membership.",
"Turkey, participates fully in both WEOG and Asian Group, but for electoral purposes is considered a member of WEOG only.",
"The United States of America is not a member of any regional group, but attends
meetings of the Western Europe and Other States Group (WEOG) as an observer and is
considered to be a member of that group for electoral purposes."))

df = df %>% 
  mutate(country = str_replace(country, "\\*", "")) %>% 
  filter(!(country == "Turkey" & un_regional_group == "Asia-Pacific Group")) %>% 
  full_join(notes)

head(df)
tail(df)

```


# Save product
```{r}
if (!dir.exists("../product_data")) {
  dir.create("../product_data")
}

write_csv(df, "../product_data/un_regional_groups.csv")
un_regional_groups = df
save(un_regional_groups, file = "../product_data/un_regional_groups.Rdata")
```

# session info

```{r}
sessionInfo()
```





